# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nesterapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nesterapp

  target 'nesterappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nesterappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
